# Generated by Django 4.1.5 on 2023-01-06 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='genre',
            field=models.ManyToManyField(related_name='genres', to='musics.genre', verbose_name='жанр'),
        ),
    ]
