# Generated by Django 4.1.5 on 2023-01-03 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='время создание')),
                ('datetime_updated', models.DateTimeField(auto_now=True, verbose_name='время обновления')),
                ('datetime_deleted', models.DateTimeField(blank=True, null=True, verbose_name='время удаления')),
                ('title', models.CharField(max_length=200, verbose_name='жанр')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='время создание')),
                ('datetime_updated', models.DateTimeField(auto_now=True, verbose_name='время обновления')),
                ('datetime_deleted', models.DateTimeField(blank=True, null=True, verbose_name='время удаления')),
                ('title', models.CharField(max_length=200, verbose_name='заголовок')),
                ('duration', models.TimeField(verbose_name='продолжительность')),
                ('status', models.CharField(choices=[('BR', 'Предрелиз'), ('R', 'Релиз'), ('AR', 'Unknown')], max_length=3, verbose_name='статус')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musics.author', verbose_name='автор')),
                ('genre', models.ManyToManyField(to='musics.genre', verbose_name='жанр')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
